# Generated by Django 3.0.3 on 2020-02-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('SSN', models.CharField(max_length=10)),
            ],
        ),
    ]
